insert into symbols (symbol, name) values ('Long-billed cockatoo', 'Cacatua tenuirostris');
insert into symbols (symbol, name) values ('Leopard, indian', 'Panthera pardus');
insert into symbols (symbol, name) values ('Moose', 'Alces alces');
insert into symbols (symbol, name) values ('Amazon parrot (unidentified)', 'Amazona sp.');
insert into symbols (symbol, name) values ('Squirrel, pine', 'Tamiasciurus hudsonicus');
insert into symbols (symbol, name) values ('Blue racer', 'Coluber constrictor foxii');
insert into symbols (symbol, name) values ('Macaque, pig-tailed', 'Macaca nemestrina');
insert into symbols (symbol, name) values ('Northern elephant seal', 'Mirounga angustirostris');
insert into symbols (symbol, name) values ('Violet-eared waxbill', 'Uraeginthus granatina');
insert into symbols (symbol, name) values ('Tasmanian devil', 'Sarcophilus harrisii');
insert into symbols (symbol, name) values ('Toucan, white-throated', 'Ramphastos tucanus');
insert into symbols (symbol, name) values ('Spurfowl, yellow-necked', 'Francolinus leucoscepus');
insert into symbols (symbol, name) values ('Rat, desert kangaroo', 'Dipodomys deserti');
insert into symbols (symbol, name) values ('Savanna baboon', 'Papio cynocephalus');
insert into symbols (symbol, name) values ('Onager', 'Equus hemionus');
insert into symbols (symbol, name) values ('Weaver, white-browed sparrow', 'Plocepasser mahali');
insert into symbols (symbol, name) values ('Hummingbird (unidentified)', 'unavailable');
insert into symbols (symbol, name) values ('Pacific gull', 'Gabianus pacificus');
insert into symbols (symbol, name) values ('Snake, green vine', 'Oxybelis fulgidus');
insert into symbols (symbol, name) values ('Tern, white-winged black', 'Chlidonias leucopterus');
insert into symbols (symbol, name) values ('Bent-toed gecko', 'Cyrtodactylus louisiadensis');
insert into symbols (symbol, name) values ('Puku', 'Kobus vardonii vardoni');
insert into symbols (symbol, name) values ('Parrot, hawk-headed', 'Deroptyus accipitrinus');
insert into symbols (symbol, name) values ('Vulture, lappet-faced', 'Aegypius tracheliotus');
insert into symbols (symbol, name) values ('Fox, bat-eared', 'Otocyon megalotis');
insert into symbols (symbol, name) values ('Vulture, white-rumped', 'Gyps bengalensis');
insert into symbols (symbol, name) values ('Waxbill, blue', 'Uraeginthus angolensis');
insert into symbols (symbol, name) values ('Sidewinder', 'Crotalus cerastes');
insert into symbols (symbol, name) values ('Reedbuck, bohor', 'Redunca redunca');
insert into symbols (symbol, name) values ('American alligator', 'Alligator mississippiensis');
insert into symbols (symbol, name) values ('Squirrel, richardson''s ground', 'Spermophilus richardsonii');
insert into symbols (symbol, name) values ('Nubian bee-eater', 'Merops nubicus');
insert into symbols (symbol, name) values ('Possum, golden brush-tailed', 'Trichosurus vulpecula');
insert into symbols (symbol, name) values ('Dromedary camel', 'Camelus dromedarius');
insert into symbols (symbol, name) values ('Thrasher, curve-billed', 'Toxostoma curvirostre');
insert into symbols (symbol, name) values ('Whale, long-finned pilot', 'Globicephala melas');
insert into symbols (symbol, name) values ('Wild turkey', 'Meleagris gallopavo');
insert into symbols (symbol, name) values ('Common ringtail', 'Pseudocheirus peregrinus');
insert into symbols (symbol, name) values ('Wagtail, african pied', 'Motacilla aguimp');
insert into symbols (symbol, name) values ('Waterbuck, defassa', 'Kobus defassa');
insert into symbols (symbol, name) values ('Duiker, gray', 'Sylvicapra grimma');
insert into symbols (symbol, name) values ('Deer, roe', 'Capreolus capreolus');
insert into symbols (symbol, name) values ('Common zebra', 'Equus burchelli');
insert into symbols (symbol, name) values ('Vervet monkey', 'Cercopithecus aethiops');
insert into symbols (symbol, name) values ('Woolly-necked stork', 'Ciconia episcopus');
insert into symbols (symbol, name) values ('Spoonbill, white', 'Platalea leucordia');
insert into symbols (symbol, name) values ('Flamingo, greater', 'Phoenicopterus ruber');
insert into symbols (symbol, name) values ('Southern right whale', 'Eubalaena australis');
insert into symbols (symbol, name) values ('Crane, black-crowned', 'Balearica pavonina');
insert into symbols (symbol, name) values ('Asian lion', 'Panthera leo persica');
